export const BlOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST';
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS';
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL';

export const BLOG_REVIEW_CREATE_REQUEST = 'BLOG_REVIEW_CREATE_REQUEST';
export const BLOG_REVIEW_CREATE_SUCCESS = 'BLOG_REVIEW_CREATE_SUCCESS';
export const BLOG_REVIEW_CREATE_FAIL = 'BLOG_REVIEW_CREATE_FAIL';
export const BLOG_REVIEW_CREATE_RESET = 'BLOG_REVIEW_CREATE_RESET';

export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST';
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS';
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL';
export const BLOG_CREATE_RESET = 'BLOG_CREATE_RESET';